### ISSUE TITLE
Repository does not reflect latest code

### ISSUE THREAD

**Issue by marksherman** [oplS15projects/KeyVentures#4]
Code in repository is from an older milestone and does not contain the whole game.

There is a racket file attached to the milestone as a binary file that appears to have later code, but doesn't work.

Your github repo should reflect your current working codebase, which I know exists.

Get it fixed so I can grade you on a final turn-in.

**Comment by justintimeforlunch** [comment]
Just uploaded. Should be all set.

**Comment by marksherman** [comment]
Why is each milestone it's own file? The repository should reflect THE PROJECT, not a file for each version. Versioning is handled by the history-tracking features of git. 

So there, ideally, would be one file, KeyVentures.rkt, or whatever you want to name it, that is the current latest state of your one-file project. Then if it changes in the future, that file is changed, and the changes are tracked by git. None of this amatuer copying-files-for-each-version mess.

Why aren't the files named .rkt? 

Having said all that, your code includes hard file locations:

```
/bin/sh: /home/justin/projects/KeyVentures/emotime/assets/emotimegui_cli: No such file or directory
```

You should try to make your code portable.

**Comment by marksherman** [comment]
I set working_directory to "./" and that resolved that point. You're all set. But your github kung fu is weak.
